[package]
name = "darn"
version = "0.1.13"
authors = ["Dr. Shahin Rostami <hello@shahinrostami.com>"]
edition = "2018"
description = "Extras for the Book on Data Analysis with Rust Notebooks"
homepage = "https://store.shahinrostami.com/product/data-analysis-with-rust-notebooks/"
license = "MIT"
repository = "https://github.com/shahinrostami/darn"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotly = "0.4.0"
nanoid = "0.3.0"
ndarray = "0.13.0"
ureq = "0.11.4"
csv = "1.1.3"
ndarray-csv ="0.4.1"
itertools = "0.9.0"
